version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: htx-interface-app:latest

  fingpt:
    build:
      context: ./fingpt
      dockerfile: Dockerfile
    image: htx-fingpt:latest
